${TEST_KERNEL}=boot():/kernel.elf

default_entry: 1
timeout: 0
verbose: yes

backdrop: 008080

/picokernel
    comment: picokernel
    protocol: limine
    path: ${TEST_KERNEL}
    cmdline: This is the first module.
